### ISSUE TITLE
IAMRoleLambdaExceution issue - more info in README required maybe?

### ISSUE THREAD

**Issue by urasni** [samchungy/valheim-aws-spot-server#4]
Hey - been trying to get this to work with absolutely no joy for the past several days now. I always get to this state in the github actions pipeline:

An error occurred: IamRoleLambdaExecution - Cannot attach a Service Role Policy to a Customer Role. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: PolicyNotAttachable; Request ID: 09aec41d-1eeb-47e1-bd43-a2cb874ee66b; Proxy: null)

IAM seems an impenetrable mess to me so I'm sure I've not set something up right, but am at a loss. Would it be possible to maybe put some info in the README about how to set up the AWS roles required to make this all work or possibly point people in the relevant direction to get the AWS account side set up in a way where this can work?

Everything else works BTW - buckets get created, lambdas copied up it's just setting up the IamRoleLambdaExecution and subsequently the  ValheimRole that's failing.

**Comment by samchungy** [comment]
Ah apologies. I was trying to narrow down the perms to use service roles but I may have mucked it up a bit. Let me see what I've messed up

**Comment by samchungy** [comment]
Give it another shot.

**Comment by urasni** [comment]
Thanks - will do this evening (tomorrow morning for you I guess. ;) )
Will let you know how it goes - appreciate you answering me so quickly. 👍

**Comment by urasni** [comment]
Now getting this: Not sure if it's because github is having issues or I need to do more than just update the serverless.yml file.

error serverless-esbuild@1.33.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.20.1"

(This is more as info than anything else - I am still trying. ;) )

**Comment by samchungy** [comment]
Ah I'll give it a run myself this afternoon. Apologies for all this.

**Comment by urasni** [comment]
No worries - I've fixed it locally by upping the node version in the workflows/deploy.yml file to 16 - I think guthub might have updated something today. Just smoothing out other account perms now - definitely got past where I was stuck before so looking good.

(I'm trying to keep IAM perms as restricted on the user account that runs the cloudformation which is why it's taking a bit more time.)

**Comment by urasni** [comment]
Sorry for the delay in getting back to you. Real life got in the way.
I now have it all working. I had to make a change to create-server.ts as well and add back in the getLatestAmazonAMI stuff as it was barfing on instancing the spot instance.

**Comment by samchungy** [comment]
Should be fixed up again
